name: kagi_kite_news_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  # Code generation for mapping between different objects with ease.
  auto_mappr_annotation: ">=2.2.0"
  # improved json serialization and data classes with full support for generics, 
  # inheritance, customization and more.
  dart_mappable: ">=4.3.0"
  # Testing library for flutter, built on top of package test.
  # A powerful HTTP networking package, supports Interceptors, Aborting and
  # canceling a request, Custom adapters, Transformers, etc.
  dio: ">=5.4.3+1" 
  # Hive is a lightweight and blazing fast key-value database written in pure Dart. 
  # Inspired by Bitcask. 
  hive_ce: ">=2.10.1"
  # Hive is a lightweight and blazing fast key-value database written in pure Dart. 
  # Inspired by Bitcask. 
  hive_ce_flutter: ">=2.2.0"
  # A Reactive State-Management and Dependency Injection Framework.
  flutter_riverpod: ">=2.6.1"
  flutter_test:
    sdk: flutter
  # Provides internationalization and localization facilities, 
  # including message translation, plurals and genders, 
  # date/number formatting and parsing, and bidirectional text.  
  intl: ">=0.20.2" 
  # A string-based path manipulation library. All of the path operations you
  # know and love, with solid support for Windows, POSIX (Linux and Mac OS X),
  # and the web.
  path: ">=1.9.0"
  # A Flutter plugin for finding commonly used locations on the filesystem. 
  # Supports Android, iOS, Linux, macOS and Windows. 
  # Not all methods are supported on all platforms.
  path_provider: ">=2.1.5"
  # A reactive caching and data-binding framework. Riverpod makes working with
  # asynchronous code a breeze.
  riverpod: ^2.6.1
  # A code generator for Riverpod. This both simplifies the syntax empowers it,
  # such as allowing stateful hot-reload.
  riverpod_annotation: ">=2.6.1"
  
dev_dependencies:
  # Code generator for auto_mappr.
  auto_mappr: ">=2.5.0"
  # Common tool for code-generation, maintained by the Dart team.
  build_runner: ">=2.4.8"
  # Builder for dart_mappable.
  dart_mappable_builder: ">=4.3.0"
  # Extension for Hive. Automatically generates TypeAdapters to store any class.
  hive_ce_generator: ">=1.8.2"
  flutter_lints: ^5.0.0
  # A Dart mock library which simplifies mocking with null safety support and no
  # manual mocks or code generation.
  mocktail: ">=1.0.4"
  # A code generator for Riverpod. This both simplifies the syntax empowers it,
  # such as allowing stateful hot-reload.
  riverpod_generator: ">=2.3.10"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
