// GENERATED CODE - DO NOT MODIFY BY HAND

// This file was generated by index_generator.
// https://github.com/BreX900/index_generator
// Run tool/index_generator.dart to update this file.

library;

export 'pages/new_home_page.dart';
export 'pages/pages.dart';
export 'providers/news_category_details_provider/fetch_new_category_details_provider.dart';
export 'providers/news_category_details_provider/news_category_details_local_data_source_provider.dart';
export 'providers/news_category_details_provider/news_category_details_provider.dart';
export 'providers/news_category_details_provider/news_category_details_remote_data_source_provider.dart';
export 'providers/news_category_details_provider/news_category_details_repository_provider.dart';
export 'providers/news_category_providers/fetch_news_category_provider.dart';
export 'providers/news_category_providers/news_category_local_data_source_provider.dart';
export 'providers/news_category_providers/news_category_remote_data_source_provider.dart';
export 'providers/news_category_providers/news_category_repository_provider.dart';
export 'widgets/error_block.dart';
export 'widgets/widgets.dart';
