// GENERATED CODE - DO NOT MODIFY BY HAND

// This file was generated by index_generator.
// https://github.com/BreX900/index_generator
// Run tool/index_generator.dart to update this file.

library;

export 'new_home_page.dart';
